#!/usr/bin/env python3
"""
{project_name} — Image Generator
Generated by generate-images skill
"""

import argparse
import io
import os
import sys
import time
from pathlib import Path

_env_file = Path(__file__).parent / ".env"
if _env_file.exists():
    for line in _env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip())

try:
    from google import genai
    from google.genai import types
    HAS_GENAI = True
except ImportError:
    HAS_GENAI = False

from PIL import Image

MODEL = "{model}"
OUTPUT_DIR = Path(__file__).parent
DELAY = {delay}
FORMAT = "{format_upper}"
QUALITY = {quality}

STYLE_PREFIX = (
    "{global_style_text} "
)

IMAGES = [
    # {images_placeholder}
]


def generate_image(client, img, output_dir, force=False):
    filepath = output_dir / img["filename"]
    if filepath.exists() and not force:
        print(f"  ⏭  Skipping {img['filename']} (exists)")
        return True

    full_prompt = STYLE_PREFIX + img["prompt"]
    print(f"  🎨 Generating {img['filename']}...")
    print(f"     Category: {img['category']}, Ratio: {img.get('aspect_ratio', 'auto')}")

    try:
        contents = []
        if img.get("reference"):
            ref_path = Path(img["reference"])
            if ref_path.exists():
                ref_image = Image.open(ref_path)
                contents.append(ref_image)
                print(f"     Reference: {ref_path}")
        contents.append(full_prompt)

        response = client.models.generate_content(
            model=MODEL,
            contents=contents,
            config=types.GenerateContentConfig(
                response_modalities=["TEXT", "IMAGE"],
            ),
        )

        for part in response.parts:
            if part.inline_data is not None:
                pil_image = Image.open(io.BytesIO(part.inline_data.data))
                pil_image.save(str(filepath), FORMAT, quality=QUALITY)
                size_kb = filepath.stat().st_size / 1024
                print(f"  ✅ {img['filename']} ({size_kb:.0f} KB)")
                return True

        print(f"  ⚠️  No image in response for {img['filename']}")
        for part in response.parts:
            if part.text:
                print(f"     Response: {part.text[:200]}")
        return False

    except Exception as e:
        print(f"  ❌ Error: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Image Generator (Gemini API)")
    parser.add_argument("--only", type=str, help="Filter by filename substring")
    parser.add_argument("--category", type=str, help="Filter by category")
    parser.add_argument("--force", action="store_true", help="Regenerate existing")
    parser.add_argument("--dry-run", action="store_true", help="Print prompts only")
    parser.add_argument("--list", action="store_true", help="List images with status")
    parser.add_argument("--delay", type=int, default=DELAY)
    args = parser.parse_args()

    images = IMAGES
    if args.only:
        images = [i for i in images if args.only in i["filename"]]
    if args.category:
        images = [i for i in images if i["category"] == args.category]

    if args.list:
        categories = {}
        for img in IMAGES:
            cat = img["category"]
            categories.setdefault(cat, []).append(img)
        for cat, cat_images in categories.items():
            print(f"\n  {cat.upper()} ({len(cat_images)}×)")
            print(f"  {'─'*50}")
            for img in cat_images:
                fp = OUTPUT_DIR / img["filename"]
                if fp.exists():
                    status = f"✅ ({fp.stat().st_size/1024:.0f} KB)"
                else:
                    status = "⬜"
                print(f"    {status}  {img['filename']}")
        total = len(IMAGES)
        existing = sum(1 for img in IMAGES if (OUTPUT_DIR / img["filename"]).exists())
        print(f"\n  Total: {existing}/{total} generated\n")
        return

    if not images:
        print("No images match the filter.")
        sys.exit(1)

    print(f"\n{'='*60}")
    print(f"  Image Generator")
    print(f"  Model: {MODEL}")
    print(f"  Images: {len(images)}")
    print(f"  Output: {OUTPUT_DIR}")
    if args.dry_run:
        print(f"  ⚡ DRY RUN")
    print(f"{'='*60}\n")

    if args.dry_run:
        for i, img in enumerate(images, 1):
            print(f"[{i}/{len(images)}] {img['filename']}")
            print(f"  Category: {img.get('category', '-')}")
            print(f"  Ratio:    {img.get('aspect_ratio', 'auto')}")
            if img.get("reference"):
                print(f"  Ref:      {img['reference']}")
            print(f"  Prompt:   {STYLE_PREFIX}{img['prompt']}")
            print()
        print(f"Total: {len(images)} images")
        return

    if not HAS_GENAI:
        print("❌ Missing google-genai. Run: pip install google-genai pillow")
        sys.exit(1)

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        print("❌ Missing GOOGLE_API_KEY")
        print("   export GOOGLE_API_KEY='your-key'")
        print("   https://aistudio.google.com/apikey")
        sys.exit(1)

    client = genai.Client()
    success = failed = 0

    for i, img in enumerate(images, 1):
        print(f"\n[{i}/{len(images)}] {img['filename']}")
        if generate_image(client, img, OUTPUT_DIR, args.force):
            success += 1
        else:
            failed += 1
        if i < len(images):
            time.sleep(args.delay)

    print(f"\n{'='*60}")
    print(f"  Done! ✅ {success} OK, ❌ {failed} failed")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
